<head>
  <style>
    .log { font-family: "Courier New", Consolas, monospace; font-size: 80%; }
    .test-failed { background-color: #ffaaaa; }
    .test-passed { background-color: #aaffaa; }
  </style>
</head>
<body>
<h3><a href="http://llhd.io/" target="_blank">moore</a></h3>
<pre class="test-failed">
description: Test imported from ivtest
rc: 101 (means success: 0)
should_fail: 0
tags: ivtest
incdirs: /tmpfs/src/github/sv-tests/third_party/tests/ivtest /tmpfs/src/github/sv-tests/third_party/tests/ivtest/ivltests
top_module: 
type: parsing
mode: parsing
files: <a href="../../../../third_party/tests/ivtest/ivltests/concat4.v.html" target="file-frame">third_party/tests/ivtest/ivltests/concat4.v</a>
time_elapsed: 0.004s
ram usage: 9700 KB
</pre>
<pre class="log">

moore -I /tmpfs/src/github/sv-tests/third_party/tests/ivtest -I /tmpfs/src/github/sv-tests/third_party/tests/ivtest/ivltests -e top <a href="../../../../third_party/tests/ivtest/ivltests/concat4.v.html" target="file-frame">third_party/tests/ivtest/ivltests/concat4.v</a>
compiler bug: lowering of call to expression not implemented
  --&gt; <a href="../../../../third_party/tests/ivtest/ivltests/concat4.v.html#l-4" target="file-frame">third_party/tests/ivtest/ivltests/concat4.v:4</a>:26-31:
   | 
   |   wire [31:0] var1 = {{0{ufunc(0)}}, ufunc(0)};
   |                          ^^^^^                 

You have encountered a compiler bug. Sorry about that! We would appreciate if you open an issue [1] and describe how you triggered the bug, together with a minimal snippet of code to reproduce it. Thanks!
[1]: https://github.com/fabianschuiki/moore

compiler bug: lowering of call to expression not implemented
  --&gt; <a href="../../../../third_party/tests/ivtest/ivltests/concat4.v.html#l-4" target="file-frame">third_party/tests/ivtest/ivltests/concat4.v:4</a>:38-43:
   | 
   |   wire [31:0] var1 = {{0{ufunc(0)}}, ufunc(0)};
   |                                      ^^^^^     

You have encountered a compiler bug. Sorry about that! We would appreciate if you open an issue [1] and describe how you triggered the bug, together with a minimal snippet of code to reproduce it. Thanks!
[1]: https://github.com/fabianschuiki/moore

error: `&lt;error&gt;` cannot be used in concatenation
  --&gt; <a href="../../../../third_party/tests/ivtest/ivltests/concat4.v.html#l-4" target="file-frame">third_party/tests/ivtest/ivltests/concat4.v:4</a>:23-36:
   | 
   |   wire [31:0] var1 = {{0{ufunc(0)}}, ufunc(0)};
   |                       ^^^^^^^^^^^^^            

thread &#39;main&#39; panicked at &#39;Internal error, cycle detected:
- __SalsaQueryDescriptor { kind: constant_value_of((n228, ParamEnv(0))) }

&#39;, &lt;::std::macros::panic macros&gt;:2:4
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

</pre>
</body>